# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/snkr/DAMASK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/snkr/DAMASK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/snkr/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/snkr/DAMASK/CMakeFiles /home/snkr/DAMASK//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/snkr/DAMASK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/snkr/DAMASK/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fortran_library

# Build rule for target.
fortran_library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fortran_library
.PHONY : fortran_library

# fast build rule for target.
fortran_library/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/fortran_library.dir/build.make src/CMakeFiles/fortran_library.dir/build
.PHONY : fortran_library/fast

#=============================================================================
# Target rules for targets named DAMASK_grid

# Build rule for target.
DAMASK_grid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DAMASK_grid
.PHONY : DAMASK_grid

# fast build rule for target.
DAMASK_grid/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/DAMASK_grid.dir/build.make src/CMakeFiles/DAMASK_grid.dir/build
.PHONY : DAMASK_grid/fast

#=============================================================================
# Target rules for targets named base64

# Build rule for target.
base64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 base64
.PHONY : base64

# fast build rule for target.
base64/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/base64.dir/build.make src/grid/CMakeFiles/base64.dir/build
.PHONY : base64/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/zlib.dir/build.make src/grid/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named VTI

# Build rule for target.
VTI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VTI
.PHONY : VTI

# fast build rule for target.
VTI/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/VTI.dir/build.make src/grid/CMakeFiles/VTI.dir/build
.PHONY : VTI/fast

#=============================================================================
# Target rules for targets named discretization_grid

# Build rule for target.
discretization_grid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 discretization_grid
.PHONY : discretization_grid

# fast build rule for target.
discretization_grid/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/discretization_grid.dir/build.make src/grid/CMakeFiles/discretization_grid.dir/build
.PHONY : discretization_grid/fast

#=============================================================================
# Target rules for targets named fft

# Build rule for target.
fft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fft
.PHONY : fft

# fast build rule for target.
fft/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/fft.dir/build.make src/grid/CMakeFiles/fft.dir/build
.PHONY : fft/fast

#=============================================================================
# Target rules for targets named spectral

# Build rule for target.
spectral: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spectral
.PHONY : spectral

# fast build rule for target.
spectral/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/spectral.dir/build.make src/grid/CMakeFiles/spectral.dir/build
.PHONY : spectral/fast

#=============================================================================
# Target rules for targets named config_c

# Build rule for target.
config_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config_c
.PHONY : config_c

# fast build rule for target.
config_c/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/config_c.dir/build.make src/grid/CMakeFiles/config_c.dir/build
.PHONY : config_c/fast

#=============================================================================
# Target rules for targets named mech_base

# Build rule for target.
mech_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mech_base
.PHONY : mech_base

# fast build rule for target.
mech_base/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/mech_base.dir/build.make src/grid/CMakeFiles/mech_base.dir/build
.PHONY : mech_base/fast

#=============================================================================
# Target rules for targets named mech_solver_basic

# Build rule for target.
mech_solver_basic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mech_solver_basic
.PHONY : mech_solver_basic

# fast build rule for target.
mech_solver_basic/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/mech_solver_basic.dir/build.make src/grid/CMakeFiles/mech_solver_basic.dir/build
.PHONY : mech_solver_basic/fast

#=============================================================================
# Target rules for targets named damask_grid_lib

# Build rule for target.
damask_grid_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 damask_grid_lib
.PHONY : damask_grid_lib

# fast build rule for target.
damask_grid_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/CMakeFiles/damask_grid_lib.dir/build.make src/grid/CMakeFiles/damask_grid_lib.dir/build
.PHONY : damask_grid_lib/fast

#=============================================================================
# Target rules for targets named stub_fortran_interface

# Build rule for target.
stub_fortran_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stub_fortran_interface
.PHONY : stub_fortran_interface

# fast build rule for target.
stub_fortran_interface/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/stub_fortran_interface.dir/build.make src/grid/test/CMakeFiles/stub_fortran_interface.dir/build
.PHONY : stub_fortran_interface/fast

#=============================================================================
# Target rules for targets named test_cpp_fortran_interface

# Build rule for target.
test_cpp_fortran_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cpp_fortran_interface
.PHONY : test_cpp_fortran_interface

# fast build rule for target.
test_cpp_fortran_interface/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_cpp_fortran_interface.dir/build.make src/grid/test/CMakeFiles/test_cpp_fortran_interface.dir/build
.PHONY : test_cpp_fortran_interface/fast

#=============================================================================
# Target rules for targets named test_discretization_grid

# Build rule for target.
test_discretization_grid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_discretization_grid
.PHONY : test_discretization_grid

# fast build rule for target.
test_discretization_grid/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_discretization_grid.dir/build.make src/grid/test/CMakeFiles/test_discretization_grid.dir/build
.PHONY : test_discretization_grid/fast

#=============================================================================
# Target rules for targets named test_fft

# Build rule for target.
test_fft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fft
.PHONY : test_fft

# fast build rule for target.
test_fft/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_fft.dir/build.make src/grid/test/CMakeFiles/test_fft.dir/build
.PHONY : test_fft/fast

#=============================================================================
# Target rules for targets named test_spectral

# Build rule for target.
test_spectral: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_spectral
.PHONY : test_spectral

# fast build rule for target.
test_spectral/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_spectral.dir/build.make src/grid/test/CMakeFiles/test_spectral.dir/build
.PHONY : test_spectral/fast

#=============================================================================
# Target rules for targets named test_mech_base

# Build rule for target.
test_mech_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mech_base
.PHONY : test_mech_base

# fast build rule for target.
test_mech_base/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_mech_base.dir/build.make src/grid/test/CMakeFiles/test_mech_base.dir/build
.PHONY : test_mech_base/fast

#=============================================================================
# Target rules for targets named test_mech_solver_basic

# Build rule for target.
test_mech_solver_basic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mech_solver_basic
.PHONY : test_mech_solver_basic

# fast build rule for target.
test_mech_solver_basic/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_mech_solver_basic.dir/build.make src/grid/test/CMakeFiles/test_mech_solver_basic.dir/build
.PHONY : test_mech_solver_basic/fast

#=============================================================================
# Target rules for targets named test_damask_grid

# Build rule for target.
test_damask_grid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_damask_grid
.PHONY : test_damask_grid

# fast build rule for target.
test_damask_grid/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_damask_grid.dir/build.make src/grid/test/CMakeFiles/test_damask_grid.dir/build
.PHONY : test_damask_grid/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f src/grid/test/CMakeFiles/test_config.dir/build.make src/grid/test/CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... DAMASK_grid"
	@echo "... VTI"
	@echo "... base64"
	@echo "... config_c"
	@echo "... damask_grid_lib"
	@echo "... discretization_grid"
	@echo "... fft"
	@echo "... fortran_library"
	@echo "... mech_base"
	@echo "... mech_solver_basic"
	@echo "... spectral"
	@echo "... stub_fortran_interface"
	@echo "... test_config"
	@echo "... test_cpp_fortran_interface"
	@echo "... test_damask_grid"
	@echo "... test_discretization_grid"
	@echo "... test_fft"
	@echo "... test_mech_base"
	@echo "... test_mech_solver_basic"
	@echo "... test_spectral"
	@echo "... zlib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/snkr/DAMASK/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

